name: gln-env
channels:
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit=10.0
  - cudatoolkit-dev=10
  - python=3.7
  - pytorch==1.2.0
  - scipy
  - tqdm
  # Dependencies below are needed to build `rdkit` from source:
  - boost
  - boost-cpp
  - cairo
  - cmake
  - eigen
  - gxx_linux-64
  - pillow
  - pkg-config
  - py-boost
  - pip:
    - torch-cluster==1.4.5
    - torch-geometric==1.3.2
    - torch-scatter==1.4.0
    - torch-sparse==0.4.3
