name: CI (integration tests)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    name: build
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        environment-file: environment_full.yml
    - name: Install syntheseus with all single-step models
      run: |
        pip install .[all]
    - name: Run single-step model tests
      run: |
        python -m pytest ./syntheseus/tests/reaction_prediction/inference/test_models.py
