name: Docs

on:
  push:
    branches: [ main ]
  workflow_call:
    inputs:
      versions:
        required: true
        type: string
      deploy:
        required: false
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git fetch origin gh-pages --depth=1
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4.9.1
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mkdocs-jupyter mike
      - if: ${{ github.event_name == 'push' || inputs.deploy }}
        run: mike deploy --push --update-aliases ${{ inputs.versions != '' && inputs.versions || 'dev' }}
      - if: ${{ github.event_name != 'push' && !inputs.deploy }}
        run: mkdocs build --strict
