name: Release Stable Version

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: write

jobs:
  push-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: |
          git tag -a v${{ inputs.version }} -m "Release v${{ inputs.version }}"
          git push origin v${{ inputs.version }}
  build-docs:
    needs: push-tag
    uses: ./.github/workflows/docs.yml
    with:
      versions: ${{ inputs.version }} stable
